######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 15 11:49:24 2009
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += src
